export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL'

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL'

export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL'

export const GET_ALL_USER_REQUEST = 'GET_ALL_USER_REQUEST'
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAIL = 'GET_ALL_USER_FAIL'

export const CURRENT_USER_REQUEST = 'CURRENT_USER_REQUEST'
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS'
export const CURRENT_USER_FAIL = 'CURRENT_USER_FAIL'

export const DONATION_CREATE_REQUEST = 'DONATION_CREATE_REQUEST'
export const DONATION_CREATE_SUCCESS = 'DONATION_CREATE_SUCCESS'
export const DONATION_CREATE_FAIL = 'DONATION_CREATE_FAIL'

export const GET_ALL_DONATION_REQUEST = 'GET_ALL_DONATION_REQUEST'
export const GET_ALL_DONATION_SUCCESS = 'GET_ALL_DONATION_SUCCESS'
export const GET_ALL_DONATION_FAIL = 'GET_ALL_DONATION_FAIL'

export const MY_DONATION_REQUEST = 'MY_DONATION_REQUEST'
export const MY_DONATION_SUCCESS = 'MY_DONATION_SUCCESS'
export const MY_DONATION_FAIL = 'MY_DONATION_FAIL'

export const DONATION_DELETE_REQUEST = 'DONATION_DELETE_REQUEST'
export const DONATION_DELETE_SUCCESS = 'DONATION_DELETE_SUCCESS'
export const DONATION_DELETE_FAIL = 'DONATION_DELETE_FAIL'

export const LOAD_MORE_REQUEST = 'LOAD_MORE_REQUEST'
export const LOAD_MORE_SUCCESS = 'LOAD_MORE_SUCCESS'
export const LOAD_MORE_FAIL = 'LOAD_MORE_FAIL'

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'